name: Main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        container: php:8.0-cli

        env:
            APP_ENV: test

        services:
            redis:
                image: redis
                ports:
                    - 6379/tcp
                # Set health checks to wait until redis has started
                options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v2

            - name: Setup and PHP extensions and Composer
              run: |
                  apt-get update && apt-get install -y zip
                  pecl install redis && docker-php-ext-enable redis
                  curl https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

            - name: Cache PHPUnit dependencies
              id: phpunit-cache
              uses: actions/cache@v2
              with:
                  path: bin/.phpunit
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/phpunit.xml.dist') }}

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Check code style
              run: vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --verbose

            - name: Run test suites
              run: bin/phpunit --testdox

            - name: Static analysis
              run: vendor/bin/phpstan analyse -c phpstan.ci.neon
